name: Docker Dev Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Dev image
      run: docker build . --file docker/Dockerfile --target app-dev --tag $IMAGE_NAME:latest
    - name: Tag the Docker Dev image
      run: docker tag open-swiss-buildings-api:latest $REGISTRY/$IMAGE_NAME:latest
    - name: Push the latest tag of the Docker Dev image
      run: docker push $REGISTRY/$IMAGE_NAME:latest
